### PR TITLE
my solution to dsa and hardware track

### PR DESCRIPTION
**Pull request by anm01-exists**
so i have done the bubble sort and something related to hardware track

### CODE REVIEW

**Comment by Haripriya-1212** [comment]
In your bubble sort code, you have made the return type of function as int, but it is not returning anything. Void would work. You can correct that and send pr.

**Comment by Haripriya-1212** [comment]
And in the arduino code, delay is repeated, it is there in toMorse function, as well as in Dot and Dash function, so double the delay. So you can fix that as well and make the pr.

**Comment by anm01-exists** [comment]
well, hopefully this fixes it

**Comment by anm01-exists** [comment]
hope, this works!!

**Comment by Haripriya-1212** [comment]
Yes!
One last thing - delay b/w different letters = 3 units, so delay(1500) after the while loop in toMorse function.

**Comment by anm01-exists** [comment]
Tried to improve the code... it can read numbers and spaces too... (fingers crossed)

**Comment by Haripriya-1212** [comment]
Yeah! works for sentences as well as numbers now. Good!

**Comment by anm01-exists** [comment]
This made my morning soo much better!! thankyou soo muchh!! you are doing a great jobb

**Pull request merged**
